# Generated by Django 5.0.2 on 2024-03-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_pet_image_bike_bike_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.CharField(choices=[('SPORT_BIKE', 'sport_bike'), ('ELECTRIC_BIKE', 'electric_bike'), ('ELECTRIC_SCOTY', 'electric_scoty'), ('ROYAL_BIKE', 'royal_bike')], max_length=20),
        ),
    ]
