# Generated by Django 5.0.2 on 2024-03-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bike_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='description',
            new_name='Features',
        ),
    ]
