# Generated by Django 5.0.2 on 2024-03-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_description_bike_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='Features',
            new_name='features',
        ),
    ]
