# Generated by Django 5.0.2 on 2024-03-11 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_features_bike_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='features',
            new_name='description',
        ),
    ]
