# Generated by Django 5.0.2 on 2024-03-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_features_bike_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.CharField(choices=[('SPORT_BIKE', 'sport_bike'), ('ELECTRIC_BIKE', 'electric_bike'), ('ELECTRIC_SCOTY', 'electric_scoty'), ('ROYAL_BIKE', 'royal_bike'), ('SHINE_BIKE', 'shine_bike'), ('UNICORN_BIKE', 'unicorn_bike'), ('ACTIVA_BIKE', 'activa_bike'), ('AVENGER_BIKE', 'avenger_bike'), ('DIO_BIKE', 'dio_bike')], max_length=20),
        ),
    ]
